apiVersion: v1
kind: Service
metadata:
  name: osticket
  labels:
    app: osticket
    group: iot
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: osticket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket
  template:
    metadata:
      labels:
        app: osticket
        group: customer
        tier: frontend
    spec:
      containers:
      - name: osticket
        image: campbellsoftwaresolutions/osticket
        env:
        - name: MYSQL_HOST
          value: osticket-mysql
        - name: MYSQL_PASSWORD
          value: secret 
        - name: SMTP-HOST
          value: mail.gmx.net
        - name: SMTP_PORT
          value: "25"
        - name: SMTP_USER
          value: "maas-test"
        - name: SMTP_PASSWORD
          value: "<notdefinedhere>"
        - name: SMTP_FROM
          value: osticket@tbz-osticket.ch
        ports:
        - containerPort: 80
          name: osticket
